name: Deploy to Staging

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: Staging
        steps:
            - name: Deploy nautilus App
              uses: appleboy/ssh-action@master

              env:
                host: ${{ secrets.SSH_HOST }} # Your server's IP address
                username: ${{ secrets.SSH_USERNAME }} # Your server's username
                key: ${{ secrets.SSH_KEY }} # Your server's SSH private key
                passphrase: ${{ secrets.SSH_PASS }} # Your server's SSH password
      
                script: |
                  cd /var/www/html/stagingnautilusshipping
                  git pull origin main
                  npm install
                  npm run build
                  sudo pm2 restart nautilusshipping